version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/pkgs/star-citizen-helper"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    commit-message:
      prefix: "chore"
      include: "scope"
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: daily
    open-pull-requests-limit: 10
    commit-message:
      prefix: "chore"
      include: "scope"
